### ISSUE TITLE
Saved tests are lost after the app is closed

### ISSUE THREAD

**Issue by shapironick** [publiclab/SmART-Form#13]
Hi @ShaneYY I just noticed that saved tests in the app are deleted from the iso version of the app after the app is quit. This could result in data loss. Once we have the timer feature going we should also make sure that that is not reset or stopped when the app is closed. Just filing this issue now to as not to forget. Have a wonderful holiday!

**Comment by ShaneYY** [comment]
Hi @shapironick The issue is solved with newest updates. Thank you!

**Comment by shapironick** [comment]
great! thanks!
