### ISSUE TITLE
Blinking green overlay on Android image capture 

### ISSUE THREAD

**Issue by shapironick** [publiclab/SmART-Form#3]
I received this comment via email:

> One thing I noticed that seemed weird on my phone (Android 7.0) was the camera capture function.
> There was a blinking green overlay on 3/4 of the image. Is that normal?

Here is screenshot:
![smartform_20170918](https://user-images.githubusercontent.com/7503343/30564421-e494fdac-9c92-11e7-8b2a-ae84d283c42d.png)

**Comment by shapironick** [comment]
Here is more clarification from the user:

> This is a Moto G4. I was using the "Before Exposure" and "After Exposure" buttons. I don't have any real badges, so was using the simulated badge PDF.

So perhaps the the triangle decal was also missing.

**Comment by ShaneYY** [comment]
Haven't tested on Moto devices before, I will try to make it adaptable in later version.

**Comment by shapironick** [comment]
Another user found the same issue on a Samsung Galaxy Grand Prime (Android version 5.0.2)

> I don’t know if this is normal, but when I open the camera to take pictures of the badges, the screen has a green shaky filter and the image is doubled. Then I clicked SNAP and then RETAKE. When I retook the picture, the image was clear and not green grainy.

This was the same brand of phone that I internal beta tested and found the same issue back in the spring.

**Comment by ebarry** [comment]
FWIW, I am looking at the SmartForm app on a Google Pixel 1 running 8.1.0 and do not see this artifact.

**Comment by ebarry** [comment]
@bronwen9 opened the photo capture app on her Motorola phone running Android 7.0 and there is a green blinking artifact, although the actual picture that is captured is fine (no green artifact)

**Comment by shapironick** [comment]
Very helpful thank you @ebarry !

**Comment by shapironick** [comment]
I think this is fixed now as a friend with a Moto was able to use it!
