### ISSUE TITLE
test location photo function lacks description (UI)

### ISSUE THREAD

**Issue by shapironick** [publiclab/SmART-Form#5]
Currently the UI of both apps lacks a clear explanation of what the test location photo function is and how to use it. 

This function could be clarified by adding the text such as: "tap here to add a photo of the test location"

Here is the current view in iso:
![screencap](https://user-images.githubusercontent.com/7503343/30566784-809c87bc-9c9b-11e7-8d77-7f12f82da04c.jpg)

And here is a suggestion enhancement (with the wrong font):

![test location](https://user-images.githubusercontent.com/7503343/30566812-9a0b3306-9c9b-11e7-8373-ceff4f67f706.jpg)

**Comment by ShaneYY** [comment]
You can get a pop-up hint by long press the block.

**Comment by shapironick** [comment]
Ah! Thank you, I didn't know that.  I wouldn't think of long pressing that space to find out more about it. Some sort of direction for the user that does not require action by the user could resolve this. I've gotten a couple inquiries from beta testers about what this function is. 

I just used the long press function for the first time and the hint text appeared towards the bottom of the screen. I like the friendly language and exclamation point of the hint text! :)
![image1](https://user-images.githubusercontent.com/7503343/30567457-75a8f4fa-9c9e-11e7-9d06-72dc907c0e48.PNG)

**Comment by ShaneYY** [comment]
Good to know about the feedbacks. I will modify the hint to be more intuitive in later version.

**Comment by gretchengehrke** [comment]
I found this confusing too, especially because it seems like it was necessary before doing anything else (at least in the iPhone version). Maybe making that clear too would be good, "First, tap here to snap a picture of the test location!" And to have that text on the icon (or instead of the icon), not as a pop-up hint.

**Comment by shapironick** [comment]
Closing this as it will be addressed in #8 and there is a question of this overview image even being necessary.
