### ISSUE TITLE
What are the international limits of both app store download permissions? 

### ISSUE THREAD

**Issue by shapironick** [publiclab/SmART-Form#6]
Karen and I received an inquiry from someone in Germany having trouble downloading the app, seemingly because of his location. Filing this issue now and will ask for more details in addition to pointing him to the drive link.

**Comment by shapironick** [comment]
We have an additional comment from Israel, saying they can't download the app.

**Comment by shapironick** [comment]
Here's a link to the public comment: https://groups.google.com/d/msg/publiclaboratory/AFS0f8ARm5w/o6q-7ThRBQAJ

**Comment by ShaneYY** [comment]
Paul has fixed the problem and updated in Google Play, the new version should be available tomorrow for all countries.
