### ISSUE TITLE
Different reported values using same badge picture with different backgrounds

### ISSUE THREAD

**Issue by gretchengehrke** [publiclab/SmART-Form#7]
I don't know all the details of this, but will update the issue as I learn them. A community member downloaded the before and after pictures, and using one background, got a reading of 75 ppb, and using a different background, got a reading of 0 ppb. I do not yet know what backgrounds she used.

**Comment by shapironick** [comment]
Thanks GG! do you know if they were using ISO or Android and what hardware and software?  

Also I'm not sure I understand what you mean by background? to you mean lighting or what the printed badge was laying on? or what was behind the monitor? Sorry for being a touch confused.

**Comment by gretchengehrke** [comment]
I am confused too. She said that the background with 75 ppb was just the room, and the background with 0 ppb was a white paper. I'm wondering if she might have just been taking pictures, rather than having downloaded the images and taking pictures of those. I'll call her later today to get clarification and will respond when I know more (and what OS she has).

**Comment by ebarry** [comment]
Is there any more information to add to this report? Or perhaps it has been resolved and we can close this?

**Comment by bihechen** [comment]
So the badge is not only the colored triangle, it containes a white background. We also adjust the photo after it is taken, and the background should always be white. This should not be a problem.

**Comment by shapironick** [comment]
I think we are not going to get any more specifics about this one-time issue as it is a year old and am going to close this issue. We could be having issues with complex lighting conditions but we need to resolve that at the level of experimentation and field validation w/ reference methods.
